/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paketim;

/**
 *
 * @author tunca
 */
public class tuncaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public tuncaJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButtonAnd = new javax.swing.JButton();
        jButtonOr = new javax.swing.JButton();
        jButtonExor = new javax.swing.JButton();
        jButtonNot = new javax.swing.JButton();
        jLabelsonuc = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        bitseltxt1 = new javax.swing.JTextField();
        bitseltxt2 = new javax.swing.JTextField();
        bitseltxt3 = new javax.swing.JTextField();
        jButtonBitselAnd = new javax.swing.JButton();
        jButtonBitselOR = new javax.swing.JButton();
        jButtonBitselNOT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hesap Makinesi"));

        jTextField2.setText("jTextField2");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jLabel1.setText("Sayı 1");

        jLabel2.setText("Sayı 2");

        jLabel3.setText("Sonuç : ");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("*");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("/");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantıksal Operatorler", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jButtonAnd.setText("And");
        jButtonAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAndActionPerformed(evt);
            }
        });

        jButtonOr.setText("Or");
        jButtonOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrActionPerformed(evt);
            }
        });

        jButtonExor.setText("EXOR");
        jButtonExor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExorActionPerformed(evt);
            }
        });

        jButtonNot.setText("NOT");
        jButtonNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotActionPerformed(evt);
            }
        });

        jLabelsonuc.setText("Sonuç");

        jCheckBox3.setText("Sonuç");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelsonuc)
                    .addComponent(jButtonAnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelsonuc)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bitwise Bitsel Operatörler", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        bitseltxt1.setText("operand A");
        bitseltxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bitseltxt1MouseClicked(evt);
            }
        });
        bitseltxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitseltxt1ActionPerformed(evt);
            }
        });

        bitseltxt2.setText("operand B");
        bitseltxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bitseltxt2MouseClicked(evt);
            }
        });
        bitseltxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitseltxt2ActionPerformed(evt);
            }
        });

        bitseltxt3.setText("sonuc");

        jButtonBitselAnd.setText("Bitsel Ve");
        jButtonBitselAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBitselAndActionPerformed(evt);
            }
        });

        jButtonBitselOR.setText("Bitsel Veya");
        jButtonBitselOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBitselORActionPerformed(evt);
            }
        });

        jButtonBitselNOT.setText("Bitsel Değil");
        jButtonBitselNOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBitselNOTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBitselNOT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bitseltxt1)
                    .addComponent(bitseltxt2)
                    .addComponent(bitseltxt3)
                    .addComponent(jButtonBitselAnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBitselOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bitseltxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bitseltxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bitseltxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBitselAnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBitselOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBitselNOT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // fare tıklayınca txtfield temizle
        // javada özellik yani proprty yok. getter ve setter metotlar var
        jTextField1.setText(""); // setter metot kullandık.
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // fare tıklayınca txtField temizle.
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // textfield1 ve 2 ye giden yazıları al sayıya dönüştür. topla ve
        // label 3 de göster
        String s1, s2, s; // nesne tipi değişken
        double sayi1, sayi2, sonuc; // temel veri tipi, metotu yok!!
        s1 = jTextField1.getText(); // getter metot
        s2 = jTextField2.getText();
        sayi1 = Double.parseDouble(s1);
        sayi2 = Double.parseDouble(s2);  
        sonuc = sayi1 + sayi2;
        jLabel3.setText(String.valueOf(sonuc)); // setter metot
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // sayı1 den sayı2 çıkarıp label3 e yazalım
        double sayi1 = Double.parseDouble(jTextField1.getText());
        double sayi2 = Double.parseDouble(jTextField2.getText());
        double sonuc = sayi1 - sayi2;
        jLabel3.setText("Sonuç: "+sonuc); // üstü kapalı tip dönüşümü
                                          // imlicit cast
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // çarpma, nesne tipi değişkenler
        Double sayi1 = Double.parseDouble(jTextField1.getText());
        Double sayi2 = Double.parseDouble(jTextField2.getText());
        Double sonuc = sayi1 * sayi2;
        jLabel3.setText("Sonuç: "+sonuc);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Bölme temel veri tipi kullanarak valueof kullanarak
        double sayi1 = Double.valueOf(jTextField1.getText());
        double sayi2 = Double.valueOf(jTextField2.getText());
        double sonuc = sayi1 / sayi2;
        jLabel3.setText("Sonuç: "+String.format("%.2f",sonuc));
        // standart C de print("
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAndActionPerformed
        // checkbox 1 ve 2 nin değerlerine VE operatörü uygulayacağız
        boolean A = jCheckBox1.isSelected();
        boolean B = jCheckBox2.isSelected(); // temel değişken
        boolean C = A && B; // VE                metot yok
        jLabelsonuc.setText("Sonuç: "+String.valueOf(C));
        jCheckBox3.setSelected(C);
    }//GEN-LAST:event_jButtonAndActionPerformed

    private void jButtonOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrActionPerformed
        // OR operatörü
        boolean A = jCheckBox1.isSelected();
        boolean B = jCheckBox2.isSelected();
        Boolean C = A || B; // OR nesne tipi boolean
        jLabelsonuc.setText("Sonuç: "+ C.toString());
        jCheckBox3.setSelected(C);
    }//GEN-LAST:event_jButtonOrActionPerformed

    private void jButtonExorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExorActionPerformed
        // EXOR operatörü
        boolean A = jCheckBox1.isSelected();
        boolean B = jCheckBox2.isSelected();
        boolean C = A ^ B; // shift 3 boşluk
        jLabelsonuc.setText("Sonuç: "+C); // üstü kapalı tip dönüşümü
        jCheckBox3.setSelected(C);
    }//GEN-LAST:event_jButtonExorActionPerformed

    private void jButtonNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotActionPerformed
        // DEĞİL operatörü
        boolean A = jCheckBox1.isSelected();
        boolean B = !A;
        jLabelsonuc.setText("Sonuç: "+B); // üstü kapalı tip dönüşümü
        jCheckBox3.setSelected(B);
    }//GEN-LAST:event_jButtonNotActionPerformed

    private void jButtonBitselAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBitselAndActionPerformed
        // 
        Integer A = Integer.parseInt(bitseltxt1.getText());
        Integer B = Integer.parseInt(bitseltxt2.getText());
        Integer C = A & B;
        // Bitwise işlemleri anlamak için sayıları ikilik tabanda görmeliyiz.
        bitseltxt1.setText(Integer.toBinaryString(A));
        bitseltxt2.setText(Integer.toBinaryString(B));
        bitseltxt3.setText(Integer.toBinaryString(C));
        //bitseltxt3.setText(C.toString());
    }//GEN-LAST:event_jButtonBitselAndActionPerformed

    private void jButtonBitselORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBitselORActionPerformed
        // bitsel veya. tam sayıları 2lik tabanda basamak basamak ve'liyoruz.
        Integer A = Integer.parseInt(bitseltxt1.getText());
        Integer B = Integer.parseInt(bitseltxt2.getText());
        Integer C = A | B;
        // bitsel veya operatörünün nasıl çalıştığını anlamak için
        // sayıları ikilik tabana çevirip basamak basamak 
        // veya işlemi uygulamamız gerekir.
        bitseltxt1.setText(Integer.toBinaryString(A));
        bitseltxt2.setText(Integer.toBinaryString(B));
        bitseltxt3.setText(Integer.toBinaryString(C));
    }//GEN-LAST:event_jButtonBitselORActionPerformed

    private void bitseltxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitseltxt1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bitseltxt1ActionPerformed

    private void bitseltxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitseltxt2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bitseltxt2ActionPerformed

    private void bitseltxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bitseltxt2MouseClicked
        // TODO add your handling code here:
        bitseltxt2.setText("");
    }//GEN-LAST:event_bitseltxt2MouseClicked

    private void bitseltxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bitseltxt1MouseClicked
        // TODO add your handling code here:
        bitseltxt1.setText("");
    }//GEN-LAST:event_bitseltxt1MouseClicked

    private void jButtonBitselNOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBitselNOTActionPerformed
        // DEĞİL operatörü bitsel
        Integer A = Integer.parseInt(bitseltxt1.getText());
        Integer B = ~A;
        // bitsel veya operatörünün nasıl çalıştığını anlamak için
        // sayıları ikilik tabana çevirip basamak basamak 
        // "değil" işlemi uygulamamız gerekir.
        bitseltxt1.setText(Integer.toBinaryString(A));
        bitseltxt2.setText(Integer.toBinaryString(B));
    }//GEN-LAST:event_jButtonBitselNOTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tuncaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tuncaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tuncaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tuncaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tuncaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bitseltxt1;
    private javax.swing.JTextField bitseltxt2;
    private javax.swing.JTextField bitseltxt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAnd;
    private javax.swing.JButton jButtonBitselAnd;
    private javax.swing.JButton jButtonBitselNOT;
    private javax.swing.JButton jButtonBitselOR;
    private javax.swing.JButton jButtonExor;
    private javax.swing.JButton jButtonNot;
    private javax.swing.JButton jButtonOr;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelsonuc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
